/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : ora
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : YANTAI

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2020-03-05 14:53:05
*/


-- ----------------------------
-- Table structure for GATE_BUSINESS
-- ----------------------------
CREATE TABLE "GATE_BUSINESS" (
"VISIT_GUID" VARCHAR2(50 CHAR) NOT NULL ,
"STATION" VARCHAR2(10 CHAR) NULL ,
"MSG" VARCHAR2(200 CHAR) NULL ,
"ARRIVE_TIME" DATE NOT NULL ,
"ENTER_TIME" DATE NULL ,
"LANE_CODE" VARCHAR2(10 CHAR) NULL ,
"RFID" VARCHAR2(20 CHAR) NULL ,
"WEIGHT" VARCHAR2(20 CHAR) NULL ,
"CNTR_SIZE" VARCHAR2(5 CHAR) NULL ,
"OCR_PLATE_NO" VARCHAR2(20 CHAR) NULL ,
"PLATE_COLOR" VARCHAR2(20 CHAR) NULL ,
"PLATE_NO" VARCHAR2(20 CHAR) NULL ,
"OCR_FRONT_CNTR_NO" VARCHAR2(20 CHAR) NULL ,
"OCR_FRONT_CONF" VARCHAR2(10 CHAR) NULL ,
"OCR_FRONT_DIRECTION" VARCHAR2(20 CHAR) NULL ,
"OCR_FRONT_ISO" VARCHAR2(10 CHAR) NULL ,
"OCR_FRONT_ISO_CONF" VARCHAR2(10 CHAR) NULL ,
"OCR_FRONT_DAMAGE" VARCHAR2(10 CHAR) NULL ,
"OCR_FRONT_EFID" VARCHAR2(10 CHAR) NULL ,
"OCR_BACK_CNTR_NO" VARCHAR2(20 CHAR) NULL ,
"OCR_BACK_CONF" VARCHAR2(10 CHAR) NULL ,
"OCR_BACK_DIRECTION" VARCHAR2(10 CHAR) NULL ,
"OCR_BACK_ISO" VARCHAR2(10 CHAR) NULL ,
"OCR_BACK_ISO_CONF" VARCHAR2(10 CHAR) NULL ,
"OCR_BACK_DAMAGE" VARCHAR2(10 CHAR) NULL ,
"OCR_BACK_EFID" VARCHAR2(10 CHAR) NULL ,
"FRONT_CNTR_NO" VARCHAR2(20 CHAR) NULL ,
"BACK_CNTR_NO" VARCHAR2(20 CHAR) NULL ,
"IMG_FOLDER" VARCHAR2(20 CHAR) NULL ,
"IMG_PATH" VARCHAR2(200 CHAR) NULL ,
"IMG_NAMES" VARCHAR2(1000 CHAR) NULL ,
"UPDATE_USER" VARCHAR2(20 CHAR) NULL ,
"OCR_FRONT_LEADSEALSTATE" VARCHAR2(45 CHAR) NULL ,
"OCR_FRONT_LEADSEALNO" VARCHAR2(45 CHAR) NULL ,
"OCR_FRONT_PROPERTY" VARCHAR2(45 CHAR) NULL ,
"OCR_BACK_LEADSEALSTATE" VARCHAR2(45 CHAR) NULL ,
"OCR_BACK_LEADSEALNO" VARCHAR2(45 CHAR) NULL ,
"OCR_BACK_PROPERTY" VARCHAR2(45 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "GATE_BUSINESS"."VISIT_GUID" IS '主键';
COMMENT ON COLUMN "GATE_BUSINESS"."MSG" IS '消息';
COMMENT ON COLUMN "GATE_BUSINESS"."ARRIVE_TIME" IS '开始时间';
COMMENT ON COLUMN "GATE_BUSINESS"."ENTER_TIME" IS '结束时间';
COMMENT ON COLUMN "GATE_BUSINESS"."LANE_CODE" IS '车道编号';
COMMENT ON COLUMN "GATE_BUSINESS"."RFID" IS 'rfid';
COMMENT ON COLUMN "GATE_BUSINESS"."WEIGHT" IS '重量';
COMMENT ON COLUMN "GATE_BUSINESS"."CNTR_SIZE" IS '集装箱数量';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_PLATE_NO" IS '识别车牌号';
COMMENT ON COLUMN "GATE_BUSINESS"."PLATE_COLOR" IS '车牌颜色';
COMMENT ON COLUMN "GATE_BUSINESS"."PLATE_NO" IS '纠正车牌号';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_CNTR_NO" IS '识别前箱号';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_CONF" IS '识别前箱号可信度';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_DIRECTION" IS '识别前箱箱门朝向';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_ISO" IS '识别前箱箱型';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_ISO_CONF" IS '识别前箱箱型可信度';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_DAMAGE" IS '识别前箱残损情况';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_EFID" IS '识别前箱空重';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_CNTR_NO" IS '识别后箱箱号';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_CONF" IS '识别后箱箱号可信度';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_DIRECTION" IS '识别后箱箱门朝向';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_ISO" IS '识别后箱箱型';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_ISO_CONF" IS '识别后箱箱型可信度';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_DAMAGE" IS '识别后箱残损情况';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_EFID" IS '识别后箱空重';
COMMENT ON COLUMN "GATE_BUSINESS"."FRONT_CNTR_NO" IS '纠正前箱箱号';
COMMENT ON COLUMN "GATE_BUSINESS"."BACK_CNTR_NO" IS '纠正后箱箱号';
COMMENT ON COLUMN "GATE_BUSINESS"."IMG_FOLDER" IS '图片文件夹名称';
COMMENT ON COLUMN "GATE_BUSINESS"."IMG_PATH" IS '图片存放ftp路径';
COMMENT ON COLUMN "GATE_BUSINESS"."IMG_NAMES" IS '图片文件名称';
COMMENT ON COLUMN "GATE_BUSINESS"."UPDATE_USER" IS '修改数据用户';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_LEADSEALSTATE" IS '前箱铅封状态';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_LEADSEALNO" IS '前箱铅封号';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_FRONT_PROPERTY" IS '前箱箱属';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_LEADSEALSTATE" IS '后箱铅封状态';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_LEADSEALNO" IS '后箱铅封号';
COMMENT ON COLUMN "GATE_BUSINESS"."OCR_BACK_PROPERTY" IS '后箱箱属';

-- ----------------------------
-- Records of GATE_BUSINESS
-- ----------------------------

-- ----------------------------
-- Indexes structure for table GATE_BUSINESS
-- ----------------------------

-- ----------------------------
-- Checks structure for table GATE_BUSINESS
-- ----------------------------
ALTER TABLE "GATE_BUSINESS" ADD CHECK ("VISIT_GUID" IS NOT NULL);
ALTER TABLE "GATE_BUSINESS" ADD CHECK ("ARRIVE_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table GATE_BUSINESS
-- ----------------------------
ALTER TABLE "GATE_BUSINESS" ADD PRIMARY KEY ("VISIT_GUID");
