server:
  port: 8085
  servlet:
    context-path: /hdGate/
#  ssl:
#    key-store: server.keystore
#    key-alias: tomcat
#    enabled: true
#    key-store-password: 123456
#    key-store-type: JKS
logging:
  config: classpath:static/config/logbak-spring.xml
  level:
    com:
      huadong:
        hdgate:
          systemManagement:
            mapper: debug

spring:
  jpa:
    show-sql: true
  profiles: #设置采用哪个配置文件
    active: prod
  mvc:
    static-path-pattern: /**  #表示所有的访问都经过静态资源路径
  resources:
    static-locations: /static/**,classpath:/static/,file:${web.img-path} #本地图片存放路径在相应application-dev/application-prod.yml中设置

mybatis:
  mapperLocations: classpath:mapper/*.xml

