spring:
  redis:
    host: localhost
    port: 6379
    password: 123
    timeout: 10000
  laneredis:
    host: localhost
    port: 6378
    timeout: 3000
main:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//127.0.0.1:1521/yantai
    username: koyomi_yt
    password: 1234
    initialSize: 5
    minIdle: 5
    maxActive: 8


web:
  img-path: D:/logTest/

xijing:
  ip: 127.0.0.1
  port: 9000


